### ISSUE TITLE
The path in windows is wrong

### ISSUE THREAD

**Issue by Lambourl** [nxxm/nxxm-docs#3]
In the windows trick the path that appears on the doc is wrong. 

<img width="747" alt="Capture d’écran 2020-09-08 à 16 56 48" src="https://user-images.githubusercontent.com/65184664/92492984-4af36200-f1f4-11ea-9033-a98262a4b065.png">

**Comment by daminetreg** [comment]
Should be fixed as by https://github.com/nxxm/nxxm-docs/commit/16a7e23797b184e04dffad3b50d7f688805132c6

**Comment by Lambourl** [comment]
@daminetreg I close this issue, it has been solved.
